### PR TITLE
Credit

### PR DESCRIPTION
**Pull request by Infernus102**

### CODE REVIEW

**Comment by daniktheboss** [comment]
I dont want to be an ass but. **** *** dude! Just because you fix small typos you want full credit for the plugin! **** *** you again the typo pull request doesnt need any credit at all!

**Comment by Aericio** [comment]
Fixing a small typo doesn't mean your an author. You didn't add major code to the plugin. He already gave you credit in the commit comments, is that not enough for you?

@DarkWav Lock please?

**Comment by Infernus102** [comment]
_[CENSORED]_

**Comment by Aericio** [comment]
Telling someone to kill themselves is kind? Stop ******** about not having your name added to the authors list in plugin.yml, he gave you credit in the commit already.

**Comment by Infernus102** [comment]
Just wanna be good to the society, idek you and you are like replying to my ****, dont ******* reply if you dont like me

**Comment by DarkWav** [comment]
//LOCKED
# **HALT.**
STOP being uncivil and rude to each other. 
I really can´t accept this behavior. 
Stop or youll end up like this guy: [Issue 16](https://github.com/DarkWav/VAC/issues/16)
@Aericio you did nothing wrong, don´t worry.
@daniktheboss please don´t use those bad words.
@Infernus102 i cannot merge this PR due to you REMOVED ME from the authors list.
and please dont tell people to kill themselfs thats uncivil.

**Pull request closed without merging**
