### PR TITLE
👻 Better ForceOP

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by DarkWav** [comment]
ill merge this. but not all changes will stay, some will be reverted. Thanks for contributing!

**Comment by DarkWav** [comment]
afterall reverted... would cause false positives on most servers!

**Comment by ghost** [comment]
okay

**Comment by DarkWav** [comment]
for example, players with a rank woud get kicked.

**Comment by ghost** [comment]
ummm that didn't happen on my server

**Pull request merged**
