### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by ZPlayzMCPE**

### CODE REVIEW

**Comment by dries-c** [comment]
wtf

**Comment by Johnmacrocraft** [comment]
...???

**Comment by 112kutiko** [comment]
update code pls

**Comment by dries-c** [comment]
use mine anticheat until this has been fixed

**Comment by dries-c** [comment]
https://github.com/Driesboy/AntiCheat

**Comment by ghost** [comment]
Lol. :D

**Comment by DarkWav** [comment]
The project has been abandoned, use Driesboy's AntiCheat if you need one. Im sorry :(.

**Comment by Johnmacrocraft** [comment]
@DarkWav ...

**Comment by dries-c** [comment]
I will continue working on my plugin today Thx for forwarding to my anticheat

**Pull request closed without merging**
