### PR TITLE
typo

### PR DESCRIPTION
**Pull request by Infernus102**

### CODE REVIEW

**Comment by DarkWav** [comment]
merged ( fix typo commit )

**Comment by Infernus102** [comment]
Wtf dude, u didn't merge it, i noticed the fucking typo, you took all the credit

**Comment by Infernus102** [comment]
That aint professional at all.

**Comment by DarkWav** [comment]
i referenced it.

**Comment by Infernus102** [comment]
Yea but i discovered it, i got no credit!

**Comment by DarkWav** [comment]
How do you define credit? I said in the commit that you made the pull request.

**Pull request closed without merging**
